apiVersion: v2
appVersion: 0.16.2
description: Submariner Kubernetes Broker
home: https://submariner-io.github.io/
maintainers:
- email: submariner-dev@googlegroups.com
  name: Contributors to the Submariner project
  url: https://submariner.io/
name: submariner-k8s-broker
sources:
- https://submariner-io.github.io/submariner-charts/charts
version: 0.16.2
