{{- if .Values.global.serviceMonitor.adservice.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    operator.insight.io/managed-by: insight
  name: adservice-monitor
spec:
  endpoints:
    - honorLabels: true
      port: http-metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: adservice
{{- end }}
