---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.name" . }}-cartservice
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
          app.kubernetes.io/component: cartservice
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cartservice
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "insight-system/insight-opentelemetry-autoinstrumentation"
    spec:
      containers:
        - name: cartservice
          image: '{{.Values.cartservice.image.registry}}/{{.Values.cartservice.image.repository}}:{{.Values.cartservice.image.tag}}'
          ports:
            - name: service
              containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: REDIS_ADDR
              value: '{{ include "redis.addr" . }}'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://my-otel-demo-otelcol:4317
            - name: CART_SERVICE_PORT
              value: '8080'
          resources:
            limits:
              memory: 160Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.name" . }}-cartservice
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "otel-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cartservice
