apiVersion: v2
appVersion: 1.0.2
description: underlay CNI solution for kubernetes
home: https://spidernet-io.github.io/spiderpool
icon: https://raw.githubusercontent.com/spidernet-io/spiderpool/main/docs/images/spider.svg
keywords:
- spiderpool
- underlay
- networking
- ipam
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: spidernet-io
  url: https://github.com/spidernet-io
name: spiderpool
sources:
- https://github.com/spidernet-io/spiderpool
type: application
version: 1.0.2
