---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  name: subnets.topohub.infrastructure.io
spec:
  group: topohub.infrastructure.io
  names:
    kind: Subnet
    listKind: SubnetList
    plural: subnets
    singular: subnet
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.ipv4Subnet.subnet
      name: SUBNET
      type: string
    - jsonPath: .spec.interface.ipv4
      name: SERVER_IP
      type: string
    - jsonPath: .status.dhcpStatus.dhcpIpTotalAmount
      name: IP_TOTAL
      type: integer
    - jsonPath: .status.dhcpStatus.dhcpIpAvailableAmount
      name: IP_AVAILABLE
      type: integer
    - jsonPath: .status.dhcpStatus.dhcpIpBindAmount
      name: IP_RESERVED
      type: integer
    - jsonPath: .spec.feature.syncHoststatus.enabled
      name: SYNC_HOSTSTATUS
      type: boolean
    - jsonPath: .spec.feature.enablePxe
      name: PXE
      type: boolean
    - jsonPath: .spec.feature.enableZtp
      name: ZTP
      type: boolean
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: Subnet is the Schema for the subnets API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SubnetSpec defines the desired state of Subnet
            properties:
              feature:
                description: Feature configuration
                properties:
                  enablePxe:
                    default: false
                    description: Enable PXE boot support
                    type: boolean
                  enableZtp:
                    default: false
                    description: Enable ZTP configuration for switch
                    type: boolean
                  syncHoststatus:
                    description: SyncHoststatus configuration
                    properties:
                      defaultClusterName:
                        description: Default cluster name
                        type: string
                      enableBindDhcpIP:
                        default: true
                        description: Enable bind dhcp ip
                        type: boolean
                      enabled:
                        default: false
                        description: Enable automatically create the hoststatus object
                          for the dhcp client. Notice, it will not be deleted automatically
                        type: boolean
                    required:
                    - enableBindDhcpIP
                    - enabled
                    type: object
                required:
                - enablePxe
                - enableZtp
                - syncHoststatus
                type: object
              interface:
                description: Interface configuration
                properties:
                  interface:
                    description: DHCP server interface (required)
                    type: string
                  ipv4:
                    description: Self IP for DHCP server (required)
                    pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$
                    type: string
                  vlanId:
                    description: VLAN ID (optional, 0-4094)
                    format: int32
                    maximum: 4094
                    minimum: 0
                    type: integer
                required:
                - interface
                - ipv4
                type: object
              ipv4Subnet:
                description: IPv4Subnet configuration
                properties:
                  dns:
                    description: DNS server (optional)
                    pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                    type: string
                  gateway:
                    description: Gateway for DHCP server (optional)
                    pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                    type: string
                  ipRange:
                    description: IPRange for DHCP server (required)
                    pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}-([0-9]{1,3}\.){3}[0-9]{1,3}(,([0-9]{1,3}\.){3}[0-9]{1,3}-([0-9]{1,3}\.){3}[0-9]{1,3})*$
                    type: string
                  subnet:
                    description: Subnet for DHCP server (required)
                    pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$
                    type: string
                required:
                - ipRange
                - subnet
                type: object
            required:
            - interface
            - ipv4Subnet
            type: object
          status:
            description: SubnetStatus defines the observed state of Subnet
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of an object's state
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              dhcpClientDetails:
                description: Dhcp client details
                type: string
              dhcpStatus:
                description: Dhcp ip status
                properties:
                  dhcpIpActiveAmount:
                    description: Number of assigned IP addresses which is in use in
                      the lease file
                    format: int64
                    type: integer
                  dhcpIpAvailableAmount:
                    description: Number of available IP addresses
                    format: int64
                    type: integer
                  dhcpIpBindAmount:
                    description: Number of reserved IP addresses which is bond to
                      MAC address
                    format: int64
                    type: integer
                  dhcpIpTotalAmount:
                    description: Total number of IP addresses in the subnet
                    format: int64
                    type: integer
                required:
                - dhcpIpActiveAmount
                - dhcpIpAvailableAmount
                - dhcpIpBindAmount
                - dhcpIpTotalAmount
                type: object
              hostNode:
                description: the name of the node who hosts the subnet
                type: string
            required:
            - dhcpClientDetails
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
