apiVersion: v2
appVersion: v2.2.1
description: A Helm chart for the kgateway project CRDs
icon: https://raw.githubusercontent.com/kgateway-dev/kgateway.dev/main/static/favicon.svg
name: kgateway-crds
type: application
version: v2.2.1
