annotations:
  addon.kpanda.io/repo: addon
  addon.kpanda.io/source: addon
apiVersion: v2
appVersion: 0.4.5
description: jenkins charts of amamba.
home: https://github.com/amamba-io/jenkins-agent
icon: https://mirrors.tuna.tsinghua.edu.cn/jenkins/art/jenkins-logo/logo.svg
keywords:
  - jenkins
  - ci
  - cd
name: jenkins
version: 0.4.5
dependencies:
  - name: jenkins
    version: "0.4.5"
    repository: "https://amamba-io.github.io/charts"
