apiVersion: v2
appVersion: v0.4.0
description: A Helm chart for ModelService in llm-d
maintainers:
  - email: jing.chen2@ibm.com
    name: Jing Chen
    url: https://github.com/jgchn
  - email: kalantar@us.ibm.com
    name: Michael Kalantar
    url: https://github.com/kalantar
name: llm-d-modelservice
sources:
  - https://github.com/llm-d-incubation/llm-d-modelservice
type: application
version: v0.4.5
dependencies:
  - name: llm-d-modelservice
    version: "v0.4.5"
    repository: "https://llm-d-incubation.github.io/llm-d-modelservice"
keywords:
- vllm
