{{- if and (not .Values.serviceAccountOverride) (or .Values.prefill .Values.decode) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-d-modelservice.pdServiceAccountName" . }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
{{- end }}
