---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.name" . }}-dataservice
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
          app.kubernetes.io/component: dataservice
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dataservice
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "insight-system/insight-opentelemetry-autoinstrumentation"
    spec:
      containers:
        - name: dataservice
          image: "{{ .Values.extensions.dataservice.image.registry }}/{{ .Values.extensions.dataservice.image.repository }}:{{ .Values.extensions.dataservice.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.extensions.dataservice.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
            - name: health-http
              containerPort: 8999
              protocol: TCP
            - name: http-metrics
              containerPort: 8888
              protocol: TCP
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://{{ include "otel-demo.name" . }}-otelcol:4317'
            - name: MYSQL_HOST
              value: '{{ include "otel-demo.name" . }}-mysql'
            {{- with .Values.extensions.dataservice.env }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}

          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.name" . }}-dataservice
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: health-http
      port: 8999
      targetPort: 8999
      protocol: TCP
    - name: http-metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "otel-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dataservice
