apiVersion: v2
appVersion: 1.3.0
dependencies:
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.2.1
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
name: ingress-nginx
type: application
version: 0.0.1
