apiVersion: v2
appVersion: v0.15.2
description: Kueue is a set of APIs and controllers for job queueing. It is a job-level
  manager that decides when a job should be admitted to start (as in pods can be created)
  and when it should stop (as in active pods should be deleted).
name: kueue
type: application
version: 0.15.2
