apiVersion: v2
appVersion: 2.2.0
dependencies:
- condition: global.enableRedis
  name: redis
  repository: file://../redis
  version: 0.0.1
description: Helm chart for deploying higress gateways
home: http://higress.io/
icon: https://higress.io/img/higress_logo_small.png
keywords:
- higress
- gateways
name: higress-core
sources:
- http://github.com/alibaba/higress
type: application
version: 2.2.0
