apiVersion: v1
appVersion: v0.12.0
description: A Helm chart for k8s prometheus adapter
home: https://github.com/kubernetes-sigs/prometheus-adapter
icon: https://raw.githubusercontent.com/cncf/artwork/master/prometheus/icon/color/prometheus-icon-color.svg
keywords:
  - hpa
  - metrics
  - prometheus
  - adapter
maintainers:
  - email: mattias.gees@jetstack.io
    name: mattiasgees
    url: https://github.com/mattiasgees
  - name: steven-sheehy
    url: https://github.com/steven-sheehy
  - email: hfernandez@mesosphere.com
    name: hectorj2f
    url: https://github.com/hectorj2f
name: prometheus-adapter
sources:
  - https://github.com/kubernetes/charts
  - https://github.com/kubernetes-sigs/prometheus-adapter
version: 5.2.1
dependencies:
  - name: prometheus-adapter
    version: "5.2.1"
    repository: "https://prometheus-community.github.io/helm-charts"
