apiVersion: v2
appVersion: v2.4.4-gitlab2
description: A Helm chart to deploy OpenBao for GitLab
keywords:
- openbao
- gitlab
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: openbao
sources:
- https://gitlab.com/gitlab-org/cloud-native/charts/openbao
type: application
version: 0.12.2
