apiVersion: v1
appVersion: 2.8.1
description: A Helm chart for Docker Registry
home: https://hub.docker.com/_/registry/
icon: https://helm.twun.io/docker-registry.png
maintainers:
  - email: devin@canterberry.cc
    name: Devin Canterberry
    url: https://canterberry.cc/
name: docker-registry
sources:
  - https://github.com/docker/distribution-library-image
version: 2.2.2
dependencies:
  - name: docker-registry
    version: "2.2.2"
    repository: "https://helm.twun.io"

keywords:
  - docker-registry

