annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Upgrade SonarQube Server to 2026.1.0"
    - kind: changed
      description: "Upgrade Chart's version to 2026.1.0"
    - kind: changed
      description: "Upgrade SonarQube Community Build to 26.1.0.118079"
    - kind: removed
      description: "Remove PostgreSQL embedded chart dependency and related settings"
    - kind: added
      description: "Support Kubernetes v1.35"
    - kind: added
      description: "Support RedHat Openshift v4.20"
    - kind: security
      description: "Update ingress-nginx subchart to v4.14.1"
    - kind: deprecated
      description: "Deprecate the ingress-nginx dependency"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube-community
      image: sonarqube:26.1.0.118079-community
    - name: sonarqube-developer
      image: sonarqube:2026.1.0-developer
    - name: sonarqube-enterprise
      image: sonarqube:2026.1.0-enterprise
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
  charts.openshift.io/name: sonarqube
apiVersion: v2
appVersion: 2026.1.0
dependencies:
- condition: nginx.enabled,ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.14.1
description: SonarQube is a self-managed, automatic code review tool that systematically
  helps you deliver clean code. As a core element of our Sonar solution, SonarQube
  integrates into your existing workflow and detects issues in your code to help you
  perform continuous code inspections of your projects. The tool analyses 30+ different
  programming languages and integrates into your CI pipeline and DevOps platform to
  ensure that your code meets high-quality standards.
home: https://www.sonarqube.org/
icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeServerLogo.png
keywords:
- coverage
- security
- code
- quality
kubeVersion: '>= 1.24.0-0'
maintainers:
- email: carmine.vassallo@sonarsource.com
  name: carminevassallo
- email: hatem.amairi@sonarsource.com
  name: hatem-amairi-sonarsource
name: sonarqube
sources:
- https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
type: application
version: 2026.1.0
