vpa:
  - "admissionController/certGen/image/registry"
  - "admissionController/image/registry"
  - "recommender/image/registry"
  - "updater/image/registry"
  - "crds/needcreate"
  - "kubeVersion"
  - "global"
  - "crds"
  - "global/vpa/imageTag"
  - "global/vpa"
  - "global/vpa/imageRegistry"
  - "admissionController/image/oldTag"
  - "recommender/image/oldTag"
  - "updater/image/oldTag"
  - "crdAvailable/image"
  - "metrics/image/repository"
  - "metrics/image/registry"
  - "createVpa/image/registry"
  - "createVpa/image/tag"
  - "metrics/image/tag"
  - "metrics"
  - "createVpa/image"
  - "metrics/image"
  - "createVpa/image/registry"
  - "createVpa"
  - "crdAvailable/image/tag"
  - "crdAvailable/image/repository"
  - "crdAvailable/image/registry"
  - "createVpa/image/repository"
  - "crdAvailable"
