- "{{ .global.hub }}/{{ .higress.higress-core.gateway.image }}:{{ .higress.higress-core.gateway.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-core.controller.image }}:{{ .higress.higress-core.controller.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-core.pilot.image }}:{{ .higress.higress-core.pilot.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-core.pluginServer.image }}:{{ .higress.higress-core.pluginServer.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-core.redis.redis.image }}:{{ .higress.higress-core.redis.redis.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-core.global.o11y.promtail.image.repository }}:{{ .higress.higress-core.global.o11y.promtail.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.image.repository }}:{{ .higress.higress-console.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.global.o11y.grafana.image.repository }}:{{ .higress.higress-console.global.o11y.grafana.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.global.o11y.prometheus.image.repository }}:{{ .higress.higress-console.global.o11y.prometheus.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.global.o11y.loki.image.repository }}:{{ .higress.higress-console.global.o11y.loki.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.certmanager.image.repository }}/cert-manager-cainjector:{{ .higress.higress-console.certmanager.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.certmanager.image.repository }}/cert-manager-controller:{{ .higress.higress-console.certmanager.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.certmanager.image.repository }}/cert-manager-webhook:{{ .higress.higress-console.certmanager.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.certmanager.image.repository }}/cert-manager-acmesolver:{{ .higress.higress-console.certmanager.image.tag }}"
- "{{ .global.hub }}/{{ .higress.higress-console.certmanager.image.repository }}/cert-manager-ctl:{{ .higress.higress-console.certmanager.image.tag }}"

