annotations:
  fips: "true"
  images: |
    - name: mariadb
      version: 12.2.2
      image: registry-1.docker.io/bitnami/mariadb:latest
    - name: mysqld-exporter
      version: 0.18.0
      image: registry-1.docker.io/bitnami/mysqld-exporter:latest
    - name: os-shell
      version: "5"
      image: registry-1.docker.io/bitnami/os-shell:latest
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 12.2.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.36.0
description: "MariaDB is an open source, community-developed SQL database server that is widely in use around the world due to its enterprise features, flexibility, and collaboration with leading tech firms."
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mariadb/img/mariadb-stack-220x234.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
maintainers:
- name: "Broadcom, Inc. All Rights Reserved."
  url: https://github.com/bitnami/charts
name: mariadb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb
version: 25.0.0
