apiVersion: v1
appVersion: 1.17.3
description: Helm chart for istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
  - istiod
  - istio-discovery
name: istiod
sources:
  - http://github.com/istio/istio
version: 1.17.3
dependencies:
  - name: istiod
    version: "1.17.3"
    repository: "https://istio-release.storage.googleapis.com/charts"
