apiVersion: v2
appVersion: 0.31.0
description: A Helm chart for JuiceFS CSI Driver
home: https://github.com/juicedata/juicefs-csi-driver
icon: https://s.juicefs.com/static/jfs/logo.svg
keywords:
  - storage
  - csi
kubeVersion: '>=1.14.0-0'
maintainers:
  - email: team@juicedata.io
    name: Juicedata Inc.
    url: https://juicefs.com
name: juicefs-csi-driver
sources:
  - https://github.com/juicedata/juicefs-csi-driver
type: application
version: 0.31.0
dependencies:
  - name: juicefs-csi-driver
    version: "0.31.0"
    repository: "https://juicedata.github.io/charts/"
