- "{{ .image.registry }}/{{ .Master.Image }}:{{ .Master.ImageTag }}"
- "{{ .image.registry }}/{{ .Agent.Image }}:{{ .Agent.ImageTag }}"
- "{{ .image.registry }}/{{ .Agent.Builder.Base.Image }}:{{ .Agent.Builder.Base.ImageTag }}-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Base.Image }}:{{ .Agent.Builder.Base.ImageTag }}-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Base.Image }}:{{ .Agent.Builder.Base.ImageTag }}"
- "{{ .image.registry }}/{{ .Agent.Builder.NodeJs.Image }}:{{ .Agent.Builder.NodeJs.ImageTag }}-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.NodeJs.Image }}:{{ .Agent.Builder.NodeJs.ImageTag }}"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk1.8-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk1.8"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk8-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk8-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.Builder.Golang.ImageTag }}-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.Builder.Golang.ImageTag }}-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.Builder.Python.ImageTag }}-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.Builder.Python.ImageTag }}"
- "{{ .trace.image.registry }}/{{ .trace.image.repository }}:{{ .trace.image.tag }}"
- "{{ .eventProxy.image.registry }}/{{ .eventProxy.image.repository }}:{{ .eventProxy.image.tag }}"

# The following content is generated from the Builder.{language}.Versions in values.yaml, see hack/update_agent_version.sh
- "{{ .image.registry }}/{{ .Agent.Builder.NodeJs.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-18.20.4-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.NodeJs.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-20.17.0-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.NodeJs.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-18.20.4-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.NodeJs.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-20.17.0-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk11-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk17-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk21-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk11-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk17-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Maven.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-jdk21-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.17.13"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.17.13-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.17.13-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.18.10-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.20.14-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.17.13-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.18.10-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Golang.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-1.20.14-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-2.7.9-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-3.10.9-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-3.11.9-ubuntu"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-2.7.9-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-3.10.9-ubuntu-podman"
- "{{ .image.registry }}/{{ .Agent.Builder.Python.Image }}:{{ .Agent.relok8sPlaceholder }}v0.4.9-3.11.9-ubuntu-podman"
