apiVersion: v1
appVersion: 5.4.9
description: Helm chart for NeuVector's core services
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - email: support@neuvector.com
    name: becitsthere
name: neuvector
sources:
  - https://github.com/neuvector/neuvector
  - https://github.com/neuvector/neuvector-helm
version: 2.8.11
dependencies:
  - name: core
    version: "2.8.11"
    repository: "https://neuvector.github.io/neuvector-helm"
keywords:
  - monitoring
  - security
  - networking
