apiVersion: v2
appVersion: v0.0.10
description: ipam for kubernetes cni
home: https://spidernet-io.github.io/spiderpool
keywords:
- spiderpool
- ipam
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: spidernet-io
  url: https://github.com/spidernet-io
name: spiderpool
sources:
- https://github.com/spidernet-io/spiderpool
type: application
version: v0.0.10
dependencies:
  - name: spiderpool
    version: "v0.0.10"
    repository: "https://spidernet-io.github.io/spiderpool"
