apiVersion: v2
appVersion: 0.3.5
description: ipam for kubernetes cni
home: https://spidernet-io.github.io/spiderpool
icon: https://raw.githubusercontent.com/spidernet-io/spiderpool/main/docs/images/spider.png
keywords:
- spiderpool
- ipam
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: spidernet-io
  url: https://github.com/spidernet-io
name: spiderpool
sources:
- https://github.com/spidernet-io/spiderpool
type: application
version: 0.3.5
dependencies:
  - name: spiderpool
    version: "0.3.5"
    repository: "https://spidernet-io.github.io/spiderpool"
keywords:
  - networking
  - ipam
