apiVersion: v2
appVersion: 0.9.0
description: A Helm chart used to deploy the event-generator in Kubernetes cluster.
name: event-generator
type: application
version: 0.1.1
dependencies:
  - name: event-generator
    version: "0.1.1"
    repository: "https://falcosecurity.github.io/charts"
keywords:
- monitoring
- security
