apiVersion: v2
appVersion: 0.10.0
description: A Helm chart used to deploy the event-generator in Kubernetes cluster.
name: falco-event-generator
type: application
version: 0.3.1
dependencies:
  - name: event-generator
    version: "0.3.1"
    repository: "https://falcosecurity.github.io/charts"
keywords:
- monitoring
- security
