apiVersion: v1
appVersion: 1.17.2
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
name: base
sources:
  - http://github.com/istio/istio
version: 1.17.2
dependencies:
  - name: base
    version: "1.17.2"
    repository: "https://istio-release.storage.googleapis.com/charts"
