gitlab:
  - "minio/registry"
  - "redis/image"
  - "redis/metrics/image"
  - "gitlab/gitlab-shell/image"
  - "global/gitlabBase/image/registry"
  - "gitlab/sidekiq/image/tag"
  - "redis/sentinel/image/registry"
  - "gitlab/webservice/image/repository"
  - "kubectl/image"
  - "gitlab/kas"
  - "postgresql/image/registry"
  - "postgresql/volumePermissions/image/registry"
  - "gitlab/gitlab-shell/image/repository"
  - "gitlab/kas/image/repository"
  - "gitlab/migrations/image/repository"
  - "kubectl/image/repository"
  - "gitlab/gitaly/image/repository"
  - "global/certificates/image/registry"
  - "gitlab/sidekiq"
  - "global/certificates/image/tag"
  - "gitlab/gitlab-shell/image/tag"
  - "gitlab/sidekiq/image"
  - "gitlab/migrations"
  - "redis/sentinel"
  - "gitlab/webservice"
  - "gitlab/migrations/image/registry"
  - "redis/sysctl/image"
  - "gitlab/migrations/image/tag"
  - "gitlab/toolbox/image/tag"
  - "postgresql/metrics/image/registry"
  - "gitlab/migrations/image"
  - "kubectl/image/registry"
  - "redis/sentinel/image"
  - "gitlab/kas/image/tag"
  - "redis/volumePermissions"
  - "gitlab/gitaly/image"
  - "postgresql/volumePermissions/image"
  - "redis/metrics/image/registry"
  - "minio/minioMc/registry"
  - "redis/sysctl"
  - "gitlab/toolbox/image"
  - "postgresql/volumePermissions"
  - "postgresql/metrics/image"
  - "gitlab/gitaly"
  - "gitlab/sidekiq/image/repository"
  - "global/gitlabBase/image/tag"
  - "redis/image/registry"
  - "gitlab/kas/image"
  - "gitlab/webservice/image/tag"
  - "kubectl/image/tag"
  - "redis/volumePermissions/image/registry"
  - "gitlab/kas/image/registry"
  - "gitlab/toolbox/image/registry"
  - "gitlab/gitaly/image/tag"
  - "gitlab/sidekiq/image/registry"
  - "gitlab/webservice/image/registry"
  - "gitlab/gitlab-shell/image/registry"
  - "gitlab/webservice/image"
  - "gitlab/gitlab-shell"
  - "gitlab/gitaly/image/registry"
  - "kubectl"
  - "redis/volumePermissions/image"
  - "minio/minioMc"
  - "redis/sysctl/image/registry"
  - "gitlab/toolbox/image/repository"
  - "minio"