{{- if .Values.npuExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npu-exporter
spec:
  selector:
    matchLabels:
      app: npu-exporter
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: npu-exporter
    spec:
      {{- with .Values.npuExporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: npu-exporter
        image: {{ include "npuExporter.fullimage" . }}
        resources: {{ toYaml .Values.resources | nindent 12 }}
        imagePullPolicy: {{ .Values.npuExporter.imagePullPolicy }}
        command: [ "/bin/bash", "-c", "--"]
        # pair firstly
        args: [ "umask 027;npu-exporter -port=8082 -ip=0.0.0.0  -updateTime=5
                 -logFile=/var/log/mindx-dl/npu-exporter/npu-exporter.log -logLevel=0 -containerMode=docker" ]
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
          runAsGroup: 0
        ports:
          - name: http
            containerPort: 8082
            protocol: TCP
        volumeMounts:
          - name: log-npu-exporter
            mountPath: /var/log/mindx-dl/npu-exporter
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: ascend-driver
            mountPath: /usr/local/Ascend/driver
            readOnly: true
          - name: ascend-dcmi
            mountPath: /usr/local/dcmi
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: docker-shim  # delete when only use containerd or isula
            mountPath: /var/run/dockershim.sock
            readOnly: true
          - name: docker  # delete when only use containerd or isula
            mountPath: /var/run/docker
            readOnly: true
          - name: cri-dockerd  # reserve when k8s version is 1.24+ and the container runtime is docker
            mountPath: /var/run/cri-dockerd.sock
            readOnly: true
          - name: containerd  # delete when only use isula
            mountPath: /run/containerd
            readOnly: true
          - name: isulad  # delete when use containerd or docker
            mountPath: /run/isulad.sock
            readOnly: true
          - name: tmp
            mountPath: /tmp
          {{- if .Values.isVirtualMachine }}
          - mountPath: /usr/sbin/dmidecode
            name: dmidecode
          {{- end }}
      volumes:
        - name: log-npu-exporter
          hostPath:
            path: /var/log/mindx-dl/npu-exporter
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: ascend-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: ascend-dcmi
          hostPath:
            path: /usr/local/dcmi
        - name: sys
          hostPath:
            path: /sys
        - name: docker-shim # delete when only use containerd or isula
          hostPath:
            path: /var/run/dockershim.sock
        - name: docker  # delete when only use containerd or isula
          hostPath:
            path: /var/run/docker
        - name: cri-dockerd # reserve when k8s version is 1.24+ and the container runtime is docker
          hostPath:
            path: /var/run/cri-dockerd.sock
        - name: containerd  # delete when only use isula
          hostPath:
            path: /run/containerd
        - name: isulad  # delete when use containerd or docker
          hostPath:
            path: /run/isulad.sock
        - name: tmp
          hostPath:
            path: /tmp
        {{- if .Values.isVirtualMachine }}
        - name: dmidecode
          hostPath:
            path: /usr/sbin/dmidecode
            type: ""
        {{- end }}
{{- end }}