{{- if eq "true" (include "gitlab.gatewayApi.route.enabled" .) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    {{- include "gitlab.commonLabels" $ | nindent 4 }}
  annotations:
    {{ .Values.gatewayRoute.annotations | toYaml | nindent 4 }}
spec:
  parentRefs:
  - name: {{ template "gitlab.gatewayApi.route.gateway" . }}
    sectionName: {{ .Values.gatewayRoute.sectionName }}
  hostnames:
    - {{ include "gitlab.kas.hostname" . | quote }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ template "gitlab.kas.serviceName" . }}
      port: {{ .Values.service.kubernetesApiPort }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.ingress.k8sApiPath | quote }}
  - backendRefs:
    - kind: Service
      name: {{ template "gitlab.kas.serviceName" . }}
      port: {{ .Values.service.externalPort }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.ingress.agentPath | quote }}
  - backendRefs:
    - kind: Service
      name: {{ template "gitlab.kas.serviceName" . }}
      port: {{ .Values.service.autoflowCodecServerApiPort }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.ingress.autoflowCodecServerApiPath | quote }}
  {{- if .Values.global.workspaces.enabled }}
  - backendRefs:
    - kind: Service
      name: {{ template "gitlab.kas.serviceName" . }}
      port: {{ .Values.service.workspacesServerPort }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.ingress.workspacesServerApiPath | quote }}
  {{- end }}
{{- end }}