{{- if and .Values.global.kas.enabled .Values.global.workspaces.enabled -}}
{{- if eq (include "gitlab.ingress.enabled" $) "true" -}}
{{- $wildcardHostname := include "gitlab.workspaces.wildcardHostname" . -}}
{{- $tlsSecret := include "workspaces.tlsSecret" . -}}
{{- $ingressCfg := dict "global" .Values.global.ingress "local" .Values.ingress "context" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-workspaces
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
  annotations:
    {{ include "ingress.class.annotation" $ingressCfg }}
    kubernetes.io/ingress.provider: "{{ template "gitlab.ingress.provider" $ingressCfg }}"
    {{- if eq "nginx" .Values.global.ingress.provider }}
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/custom-http-errors: ""
    {{- end }}
    {{- include "gitlab.certmanager_annotations" . | nindent 4 }}
  {{- range $key, $value := merge .Values.ingress.annotations .Values.global.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{ include "ingress.class.field" $ingressCfg }}
  rules:
    - host: {{ $wildcardHostname | quote }}
      http:
        paths:
          - path: "/"
            pathType: {{ default "Prefix" $.Values.global.ingress.pathType }}
            backend:
              service:
                name: {{ template "gitlab.kas.serviceName" . }}
                port:
                  number: {{ .Values.service.workspacesServerPort }}
  {{- if (and $tlsSecret (eq (include "gitlab.ingress.tls.enabled" $) "true" )) }}
  tls:
    - hosts:
      - {{ $wildcardHostname | quote }}
      secretName: {{ $tlsSecret }}
  {{- end }}
{{- end -}}
{{- end -}}
