apiVersion: v2
appVersion: v0.21.0
description: A Helm chart for kubean
icon: https://avatars.githubusercontent.com/u/108458246
name: kubean
type: application
version: v0.21.0
dependencies:
  - name: kubean
    version: "v0.21.0"
    repository: "https://kubean-io.github.io/kubean-helm-chart"
annotations:
  addon.kpanda.io/namespace: kubean-system
  addon.kpanda.io/release-name: kubean
keywords:
  - kubean
  - kubespray
