apiVersion: v2
appVersion: v18.7.0
dependencies:
- name: gitlab
  repository: ""
  version: '*.*.*'
- name: certmanager-issuer
  repository: ""
  version: '*.*.*'
- name: minio
  repository: ""
  version: '*.*.*'
- name: registry
  repository: ""
  version: '*.*.*'
- alias: certmanager
  condition: installCertmanager
  name: cert-manager
  repository: https://charts.jetstack.io/
  version: v1.17.4
- condition: prometheus.install
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 27.50.1
- condition: postgresql.install
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.4.4
- condition: gitlab-runner.install
  name: gitlab-runner
  repository: https://charts.gitlab.io/
  version: 0.83.3
- condition: redis.install
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.19.4
- condition: nginx-ingress.enabled
  name: nginx-ingress
  repository: ""
  version: '*.*.*'
- alias: nginx-ingress-geo
  condition: nginx-ingress-geo.enabled
  name: nginx-ingress
  repository: ""
  version: '*.*.*'
- condition: gitlab-zoekt.install
  name: gitlab-zoekt
  repository: https://charts.gitlab.io/
  version: 3.7.1
- condition: openbao.install
  name: openbao
  repository: https://charts.gitlab.io/
  version: 0.10.0
- condition: traefik.install
  name: traefik
  repository: https://helm.traefik.io/traefik
  version: 10.19.4
- alias: haproxy
  condition: haproxy.install
  name: kubernetes-ingress
  repository: https://haproxytech.github.io/helm-charts
  version: 1.39.4
- alias: envoy-gateway
  condition: global.gatewayApi.installEnvoy
  name: gateway-helm
  repository: oci://registry-1.docker.io/envoyproxy
  version: 1.6.0
description: GitLab is the most comprehensive AI-powered DevSecOps Platform.
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
keywords:
- gitlab
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: gitlab
sources:
- https://gitlab.com/gitlab-org/charts/gitlab
version: 9.7.0
