apiVersion: v2
appVersion: 0.3.0
description: egressgateway
home: https://spidernet-io.github.io/agent
keywords:
  - egressgateway
kubeVersion: '>= 1.16.0-0'
maintainers:
  - name: spidernet-io
    url: https://github.com/spidernet-io
name: egressgateway
sources:
  - https://github.com/spidernet-io/egressgateway
type: application
version: 0.3.0
dependencies:
  - name: egressgateway
    version: "0.3.0"
    repository: "https://spidernet-io.github.io/egressgateway"
