apiVersion: v2
appVersion: 1.10.6
description: A Helm chart for KubeVela core
home: https://kubevela.io
icon: https://kubevela.io/img/logo.svg
name: vela-core
type: application
version: 1.10.6
dependencies:
  - name: vela-core
    version: "1.10.6"
    repository: "https://kubevela.github.io/charts"
keywords:
  - oam
