apiVersion: v2
appVersion: 1.9.11
description: A Helm chart for KubeVela core
home: https://kubevela.io
icon: https://kubevela.io/img/logo.svg
name: vela-core
type: application
version: 1.9.11
dependencies:
  - name: vela-core
    version: "1.9.11"
    repository: "https://kubevela.github.io/charts"
keywords:
  - oam
