apiVersion: v2
appVersion: 0.41.0
dependencies:
- condition: falcosidekick.enabled
  name: falcosidekick
  repository: https://falcosecurity.github.io/charts
  version: 0.9.*
- condition: collectors.kubernetes.enabled
  name: k8s-metacollector
  repository: https://falcosecurity.github.io/charts
  version: 0.1.*
- condition: falcotalon.enabled
  name: falco-talon
  repository: https://falcosecurity.github.io/charts
  version: 0.2.*
description: Falco
home: https://falco.org
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: cncf-falco-dev@lists.cncf.io
  name: The Falco Authors
name: falco
sources:
- https://github.com/falcosecurity/falco
version: 4.22.0
