apiVersion: v2
appVersion: 0.1.9
description: meta-plugins works with macvlan cni to solve some communication problems
  when macvlan is used as CNI.
maintainers:
- name: Spider-Guys
name: meta-plugins
sources:
- https://github.com/spidernet-io/cni-plugins
type: application
version: 0.1.9
