apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbao.fullname" . }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openbao.selectorLabels" . | nindent 6 }}
  strategy:
    # Use the 'recreate' strategy to ensure that all pods are shut down before creating new ones.
    # This prevents older OpenBao version from becoming leader after a new OpenBao version modified data.
    # This implies downtime during the upgrade process.
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{ include "openbao.monitoring.annotations" $ | nindent 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openbao.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openbao.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostAliases:
        - hostnames:
          - {{ include "gitlab.openbao.hostname" . }}
          ip: "127.0.0.1"
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - bao
            - server 
            - -config=/srv/openbao/config.json
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.config.apiPort }}
              protocol: TCP
            {{- if and .Values.config.telemetry.enabled .Values.config.metricsListener.enabled }}
            - name: metrics
              containerPort: {{ .Values.config.metricsListener.port }}
              protocol: TCP
            {{- end }}
          env:
            - name: BAO_ADDR
              value: {{ include "openbao.internalUrl" . | quote }}
            {{- with (include "openbao.postgresql.configuration" . | fromYaml).password }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secret }}
                  key: {{ .key }}
            {{- end }}
            {{- include "openbao.serviceRegistration.env" . | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /srv/openbao/config.json
              subPath: config.json
              readOnly: true
            {{- if not .Values.config.tlsDisable }}
            - name: tls
              mountPath: /srv/openbao/tls/
              readOnly: true
            {{- end }}
        {{- if .Values.unsealer.enabled }}
        - name: {{ .Chart.Name }}-unsealer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["/srv/openbao/scripts/unsealer.sh"]
          env:
          - name: BAO_ADDR
            value: {{ include "openbao.internalUrl" . | quote }}
          volumeMounts:
            - name: unseal-script
              mountPath: /srv/openbao/scripts/unsealer.sh
              subPath: unsealer.sh
              readOnly: true
            - name: unseal-keys
              mountPath: /srv/openbao/keys/
              readOnly: true
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "openbao.fullname" . }}-config
        {{- if .Values.unsealer.enabled }}
        - name: unseal-script
          projected:
            sources:
            - configMap:
                name: {{ template "openbao.fullname" . }}-unseal
                items:
                  - key: unsealer.sh
                    path: unsealer.sh
                    mode: 0550
        - name: unseal-keys
          projected:
            sources:
            {{- .Values.unsealer.sources | toYaml | nindent 12 }}
        {{- end }}
        {{- if not .Values.config.tlsDisable }}
        - name: tls
          secret:
            secretName: {{ include "gitlab.openbao.tlsSecret" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
