apiVersion: v2
appVersion: 6.4.3
description: An automated observability platform for cloud-native developers.
home: https://github.com/deepflowio/deepflow
icon: https://raw.githubusercontent.com/deepflowio/deepflow-charts/main/deepflow.svg
keywords:
  - deepflow
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: deepflow
    url: https://github.com/deepflowio/deepflow
name: deepflow
sources:
  - https://github.com/deepflowio/deepflow
type: application
version: 6.4.004
dependencies:
  - name: deepflow
    version: "v6.4.004"
    repository: "https://deepflowio.github.io/deepflow"
