apiVersion: v2
appVersion: 0.3.0
description: spiderdoctor
home: https://spidernet-io.github.io/agent
keywords:
  - spiderdoctor
kubeVersion: '>= 1.16.0-0'
maintainers:
  - name: spidernet-io
    url: https://github.com/spidernet-io
name: spiderdoctor
sources:
  - https://github.com/spidernet-io/spiderdoctor
type: application
version: 0.3.0
dependencies:
  - name: spiderdoctor
    version: "0.3.0"
    repository: "https://spidernet-io.github.io/spiderdoctor"
