spiderdoctor:
  global:
    imageRegistryOverride: "ghcr.m.daocloud.io"

  spiderdoctorAgent:
    image:
      repository: spidernet-io/spiderdoctor/agent

    service:
      type: NodePort

    podAnnotations: {}

  spiderdoctorController:
    image:
      repository: spidernet-io/spiderdoctor/controller

  feature:
    enableIPv4: true

    enableIPv6: false

    nethttp_defaultRequest_MaxQps: 100

    crdMaxHistory: 10

    aggregateReport:
      enabled: true

      controller:
        reportHostPath: "/var/run/spiderdoctor/reports"

        maxAgeInDay: 30

        # for store report
        pvc:
          enabled: false

          storageClass: ""

          storageRequests: "100Mi"

          storageLimits: "1024Mi"
