# Default values for dce-multus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

multus:
  pod:
    resources:
      enabled: false
      multus:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
  labels:
    nodeSelector:
      kubernetes.io/arch: amd64

  image:
    repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/multus-cni
    tag: v3.9

  config:
    cni_conf:
      name: multus-cni-network
      type: multus
      kubeconfig: /etc/cni/net.d/multus.d/multus.kubeconfig
      cniVersion: 0.3.1
      confDir: /etc/cni/net.d
      cniDir: /var/lib/cni/multus
      binDir: /opt/cni/bin
      logFile: /var/log/multus.log
      # -- info,debug,error,verbose,panic
      logLevel: info
      capabilities:
        portMappings: true
      readinessindicatorfile: ""
      namespaceIsolation: false
      # -- calico or cilium
      clusterNetwork: calico
      defaultNetwork: []
      delegates: []
      systemNamespaces: ["kube-system"]

overlay_crds:
  calico:
    name: calico
    enable: true
  cilium:
    name: cilium
    enable: true
  k8s-pod-network:
    name: k8s-pod-network
    enable: true

cluster_subnet:
  service_subnet:
    ipv4: "10.233.0.0/18"
    ipv6: ""
  pod_subnet: ["10.233.64.0/18"]
  rp_filter:
    set_host: true
    value: 2

macvlan:
  enable: true
  type: macvlan-overlay
  name: macvlan-vlan0
  master: "ens192"
  vlanID: 0
  migrate_route: -1
  overlayInterface: eth0
  custom_route: []
  skip_call: false

sriov:
  images:
    registry: docker.io
    sriovCni:
      repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-cni
      tag: v2.6.3
    sriovDevicePlugin:
      repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-network-device-plugin
      tag: v3.5.1
    pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    #create: true
    # Annotations to add to the service account
    #annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: sriov-device-plugin-test

  pod:
    resources:
      enabled: true
      sriov_cni:
        requests:
          memory: "50Mi"
          cpu: "100m"
        limits:
          memory: "50Mi"
          cpu: "100m"

  labels:
    nodeSelector:
      kubernetes.io/arch: amd64

  config:
    scMountPaths:
      cnibin: "/host/opt/cni/bin"
    sdpMountPaths:
      deviceSock: "/var/lib/kubelet"
      log: "/var/log"
      configVolume: "/etc/pcidp/"
      deviceInfoPath: "/var/run/k8s.cni.cncf.io/devinfo/dp"
    sriov_device_plugin:
      name: sriov_netdevice
      resourcePrefix: intel.com
      vendors: ["8086"]
      devices: ["154c"]
      drivers: []
      pfNames: []

  sriov_crd:
    type: sriov-overlay
    name: sriov-vlan0
    vlanId: 0
    overlayInterface: eth0
    custom_route: []
    skip_call: false
    migrate_route: -1

  manifests:
    enable: false
    serviceAccount: true
    configMap_sriov_device_plugin: true
    daemonSet_sriov_device_plugin: true
    daemonSet_sriov_cni: true
    net_attach_def_netdev: false
    net_attach_def_dpdk: false

meta-plugins:
  image:
    repository: ghcr.m.daocloud.io/spidernet-io/cni-plugins/meta-plugins
    tag: ""
