vela-core:
  - "image/registry"
  - "multicluster/clusterGateway/image/registry"
  - "admissionWebhooks/patch/image/registry"
  - "test/k8s/registry"
  - "test/app/registry"
  - "fluxcd"
  - "fluxcd/helm_controller"
  - "fluxcd/helm_controller/image"
  - "fluxcd/helm_controller/image/registry"
  - "fluxcd/helm_controller/image/repository"
  - "fluxcd/helm_controller/image/tag"
  - "fluxcd/image_automation_controller"
  - "fluxcd/image_automation_controller/image"
  - "fluxcd/image_automation_controller/image/registry"
  - "fluxcd/image_automation_controller/image/repository"
  - "fluxcd/image_automation_controller/image/tag"
  - "fluxcd/image_reflector_controller"
  - "fluxcd/image_reflector_controller/image"
  - "fluxcd/image_reflector_controller/image/registry"
  - "fluxcd/image_reflector_controller/image/repository"
  - "fluxcd/image_reflector_controller/image/tag"
  - "fluxcd/kustomize_controller"
  - "fluxcd/kustomize_controller/image"
  - "fluxcd/kustomize_controller/image/registry"
  - "fluxcd/kustomize_controller/image/repository"
  - "fluxcd/kustomize_controller/image/tag"
  - "fluxcd/source_controller"
  - "fluxcd/source_controller/image"
  - "fluxcd/source_controller/image/registry"
  - "fluxcd/source_controller/image/repository"
  - "fluxcd/source_controller/image/tag"