
apiVersion: kubean.io/v1alpha1
kind: Manifest
metadata:
  name: "manifest-v0-32-4"
  labels:
    kubean.io/sprayRelease: master
  annotations:
    helm.sh/resource-policy: keep
spec:
  kubesprayVersion: "8dacb9cd169ca4b1fbac75290543ca5d70d4353c"
  kubeanVersion: "v0.32.4"
  docker:
    - os: redhat
      defaultVersion: "28.3"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
        - "27.0"
        - "27.1"
        - "27.2"
        - "27.3"
        - "27.4"
        - "27.5"
        - "28.0"
        - "28.1"
        - "28.2"
        - "28.3"
    - os: debian
      defaultVersion: "28.3"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "25.0"
        - "26.0"
        - "26.1"
        - "27.0"
        - "27.1"
        - "27.2"
        - "27.3"
        - "27.4"
        - "27.5"
        - "28.0"
        - "28.1"
        - "28.2"
        - "28.3"
    - os: ubuntu
      defaultVersion: "28.3"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
        - "27.0"
        - "27.1"
        - "27.2"
        - "27.3"
        - "27.4"
        - "27.5"
        - "28.0"
        - "28.1"
        - "28.2"
        - "28.3"
    - os: kylin
      defaultVersion: "26.1"
      versionRange:
        - "18.09"
        - "19.03"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
  components:
    - name: cilium
      defaultVersion: "1.18.5"
      versionRange: []
    - name: flannel
      defaultVersion: "0.27.3"
      versionRange: []
    - name: kube_ovn
      defaultVersion: "1.12.21"
      versionRange: []
    - name: runc
      defaultVersion: "1.3.4"
      versionRange:
        - "1.3.4"
        - "1.3.3"
        - "1.3.2"
        - "1.3.1"
        - "1.3.0"
        - "1.2.9"
        - "1.2.8"
        - "1.2.7"
        - "1.2.6"
        - "1.2.5"
        - "1.2.4"
        - "1.2.3"
        - "1.2.2"
        - "1.2.1"
        - "1.2.0"
        - "1.1.15"
        - "1.1.14"
        - "1.1.13"
        - "1.1.12"
        - "1.1.11"
        - "1.1.10"
        - "1.1.9"
        - "1.1.8"
    - name: kube
      defaultVersion: "1.32.9"
      versionRange:
        - "1.34.3"
        - "1.34.2"
        - "1.34.1"
        - "1.34.0"
        - "1.33.7"
        - "1.33.6"
        - "1.33.5"
        - "1.33.4"
        - "1.33.3"
        - "1.33.2"
        - "1.33.1"
        - "1.33.0"
        - "1.32.11"
        - "1.32.10"
        - "1.32.9"
        - "1.32.8"
        - "1.32.7"
        - "1.32.6"
        - "1.32.5"
        - "1.32.4"
        - "1.32.3"
        - "1.32.2"
        - "1.32.1"
        - "1.32.0"
    - name: cni
      defaultVersion: "1.8.0"
      versionRange:
        - "1.8.0"
        - "1.7.1"
        - "1.6.2"
        - "1.6.0"
    - name: calico
      defaultVersion: "3.30.5"
      versionRange:
        - "3.30.5"
        - "3.30.4"
        - "3.30.3"
        - "3.30.2"
        - "3.30.1"
        - "3.30.0"
        - "3.29.7"
        - "3.29.6"
        - "3.29.5"
        - "3.29.4"
        - "3.29.3"
        - "3.29.2"
        - "3.29.1"
        - "3.29.0"
        - "3.28.5"
        - "3.28.4"
        - "3.28.3"
        - "3.28.2"
        - "3.28.1"
        - "3.28.0"
    - name: containerd
      defaultVersion: "2.2.1"
      versionRange:
        - "2.2.1"
        - "2.2.0"
        - "2.1.6"
        - "2.1.5"
        - "2.1.4"
        - "2.1.3"
        - "2.1.2"
        - "2.1.1"
        - "2.1.0"
        - "2.0.7"
        - "2.0.6"
        - "2.0.5"
        - "2.0.4"
        - "2.0.3"
        - "2.0.2"
        - "2.0.1"
        - "2.0.0"
        - "1.7.30"
        - "1.7.29"
        - "1.7.28"
        - "1.7.27"
        - "1.7.26"
        - "1.7.25"
        - "1.7.24"
        - "1.7.23"
        - "1.7.22"
        - "1.7.21"
        - "1.7.20"
        - "1.7.19"
        - "1.7.18"
        - "1.7.17"
        - "1.7.16"
        - "1.7.15"
        - "1.7.14"
        - "1.7.13"
        - "1.7.12"
        - "1.7.11"
        - "1.7.10"
        - "1.7.9"
        - "1.7.8"
        - "1.7.7"
        - "1.7.6"
        - "1.7.5"
        - "1.7.4"
        - "1.7.3"
        - "1.7.2"
        - "1.7.1"
        - "1.7.0"
