apiVersion: v2
appVersion: 0.11.0
description: A Helm chart for Kubernetes Vertical Pod Autoscaler
maintainers:
  - name: sudermanjr
name: vpa
type: application
version: 1.5.0
dependencies:
  - name: vpa
    version: "1.5.0"
    repository: "https://charts.fairwinds.com/stable"
annotations:
  addon.kpanda.io/namespace: kube-system
  addon.kpanda.io/release-name: vpa
keywords:
  - vpa
  - autoscale
