apiVersion: v2
appVersion: 1.4.1
description: A Helm chart for Kubernetes Vertical Pod Autoscaler
home: https://github.com/FairwindsOps/charts/tree/master/stable/vpa
kubeVersion: '>= 1.24.0-0'
maintainers:
  - name: sudermanjr
name: vpa
sources:
  - https://github.com/FairwindsOps/charts/tree/master/stable/vpa
  - https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
type: application
version: 4.10.1
dependencies:
  - name: vpa
    version: "4.10.1"
    repository: "https://charts.fairwinds.com/stable"
annotations:
  addon.kpanda.io/namespace: kube-system
  addon.kpanda.io/release-name: vpa
keywords:
  - vpa
  - autoscale
