annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: '>=1.19'
apiVersion: v2
appVersion: 0.1.31
description: Kubernetes cluster visualiser and graphical explorer
home: https://github.com/benc-uk/kubeview
icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
maintainers:
  - email: sebastien.prudhomme@gmail.com
    name: sebastien-prudhomme
name: kubeview
sources:
  - https://github.com/benc-uk/kubeview
  - https://github.com/cowboysysop/charts/tree/master/charts/kubeview
version: 3.1.0
dependencies:
  - name: kubeview
    version: "3.1.0"
    repository: "https://cowboysysop.github.io/charts/"
keywords:
- hpa
