apiVersion: v2
appVersion: v18.8.2
description: GitLab is the most comprehensive AI-powered DevSecOps Platform.
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
keywords:
  - gitlab
maintainers:
  - email: support@gitlab.com
    name: GitLab Inc.
name: gitlab
sources:
  - https://gitlab.com/gitlab-org/charts/gitlab
version: 9.8.2
dependencies:
  - name: gitlab
    version: "9.8.2"
    repository: "https://charts.gitlab.io/"
