apiVersion: v1
appVersion: v18.0.0
description: GitLab is the most comprehensive AI-powered DevSecOps Platform.
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
keywords:
  - gitlab
maintainers:
  - email: support@gitlab.com
    name: GitLab Inc.
name: gitlab
sources:
  - https://gitlab.com/gitlab-org/charts/gitlab
version: 9.0.0
dependencies:
  - name: gitlab
    version: "9.0.0"
    repository: "https://charts.gitlab.io/"
