apiVersion: v2
appVersion: 2.2.0
description: Helm chart for deploying Higress gateways
home: http://higress.io/
icon: https://higress.io/img/higress_logo_small.png
keywords:
  - networking
  - higress
  - gateways
name: higress
sources:
  - http://github.com/alibaba/higress
type: application
version: 2.2.0
dependencies:
  - name: higress
    version: "2.2.0"
    repository: "https://higress.cn/helm-charts"
