apiVersion: v1
kind: Service
metadata:
  name: {{ template "monkeys.server.fullname" . }}
  labels:
{{ include "monkeys.labels" . | indent 4 }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
    component: "server"
{{- with .Values.server.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.server.service.clusterIP }}
  clusterIP: {{ .Values.server.service.clusterIP }}
  {{- end }}
  ports:
    - name: http-server
      port: {{ .Values.server.service.port }}
      protocol: TCP
      targetPort: http-server
  selector:
{{ include "monkeys.selectorLabels" . | indent 4 }}
    component: "server"
