apiVersion: {{ ternary "storage.k8s.io/v1" "storage.k8s.io/v1beta1" (semverCompare ">=1.18.0-0" .Capabilities.KubeVersion.Version) }}
kind: CSIDriver
metadata:
  name: {{ include "driverName" . }}
  annotations:
    {{- if not .Values.csidriver.disableHooks }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    "helm.sh/resource-policy": keep
    {{- with .Values.csidriver.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  attachRequired: false
  podInfoOnMount: true
