apiVersion: v2
appVersion: 0.40.0
description: Falco
home: https://falco.org
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
maintainers:
  - email: cncf-falco-dev@lists.cncf.io
    name: The Falco Authors
name: falco
sources:
  - https://github.com/falcosecurity/falco
version: 4.20.0
dependencies:
  - name: falco
    version: "4.20.0"
    repository: "https://falcosecurity.github.io/charts"
