apiVersion: v2
appVersion: 1.22.0
dependencies:
  - name: contour
    repository: https://charts.bitnami.com/bitnami
    version: 9.1.1
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
name: contour
type: application
version: 9.1.1
keywords:
  - networking
  - ingress
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
