annotations:
  category: Infrastructure
  images: |
    - name: contour
      image: docker.io/bitnami/contour:1.32.1-debian-12-r0
    - name: envoy
      image: docker.io/bitnami/envoy:1.34.5-debian-12-r0
    - name: nginx
      image: docker.io/bitnami/nginx:1.29.1-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 1.32.1
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/contour/img/contour-stack-220x234.png
keywords:
  - networking
  - ingress
  - envoy
  - contour
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: contour
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/contour
version: 21.1.4
dependencies:
  - name: contour
    version: "21.1.4"
    repository: "https://charts.bitnami.com/bitnami"
