apiVersion: v2
appVersion: 1.23.3
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
name: contour
type: application
version: 10.2.2
keywords:
  - networking
  - ingress
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
dependencies:
  - name: contour
    version: "10.2.2"
    repository: "https://charts.bitnami.com/bitnami"
