# if your local host is not reachable to Opensource Chart, you could trigger this to build /charts/$PROJECT/$PROJECT
name: Call Generate Chart

env:
  MERGE_BRANCH: main
  PR_LABEL: pr/release/robot_update_chart
  PR_REVIWER: weizhoublue

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project name'
        required: true
      ref:
        description: 'branch name, tag or sha'
        required: true
        default: main

permissions: write-all

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      # some event, the tag is not sha, so checkout it and get sha
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.ref }}

      - name: Result Ref
        id: result
        run: |
          ref=$( git show -s --format='format:%H')
          echo ::set-output name=ref::${ref}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with: 
          version: 'v3.19.2'

      - name: Install helm-schema-gen
        run: |
          helm plugin install https://github.com/karuppiah7890/helm-schema-gen.git

      - name: generate chart
        run: |
              [ ! -d "charts/${{ github.event.inputs.project }}" ] && echo "error, failed to find project ${{ github.event.inputs.project }} under /charts " && exit 1
              make -e PROJECT=${{ github.event.inputs.project }}

      - name: package chart
        id: package_chart
        run: |
          ROOT_DIR=`pwd`
          mkdir _upload
          cd _upload
          helm package ${ROOT_DIR}/charts/${{ github.event.inputs.project }}/${{ github.event.inputs.project }}
          FILENAME=`ls *.tgz`
          echo ::set-output name=filepath::${ROOT_DIR}/_upload/${FILENAME}

      - name: Upload chart artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: charts
          path: ${{ steps.package_chart.outputs.filepath }}
          retention-days: 1

  # update /index.yaml in the target branch
  create_pr:
    runs-on: ubuntu-latest
    needs: [ package ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.MERGE_BRANCH }}
          persist-credentials: "true"

      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: charts
          path: ./charts/${{ github.event.inputs.project }}

      - name: prepare
        run: |
          cd charts/${{ github.event.inputs.project }}
          rm -rf ${{ github.event.inputs.project }}
          tar xzvf *.tgz
          rm -f *.tgz

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          title: "robot Update ${{ github.event.inputs.project }} chart to branch ${{ env.MERGE_BRANCH }} "
          commit-message: "robot Update ${{ github.event.inputs.project }} chart to branch ${{ env.MERGE_BRANCH }} "
          branch-suffix: timestamp
          branch: robot/update_chart
          delete-branch: true
          base: ${{ env.MERGE_BRANCH }}
          signoff: true
          token: ${{ secrets.WELAN_PAT }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}
