inferencepool:
  - "inferencePool/modelServers/matchLabels/app"
  - "inferencePool/modelServers/matchLabels"
  - "inferencePool/modelServers"
  - "inferenceExtension/resources/requests/cpu"
  - "inferenceExtension/resources/requests/memory"
  - "inferenceExtension/resources/requests"
  - "inferenceExtension/resources"
  - "inferenceExtension/resources/limits/cpu"
  - "inferenceExtension/resources/limits/memory"
  - "inferenceExtension/resources/limits"

